### ISSUE TITLE
Create rubric drafts for additional visibility points

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/CMCS-DSG-DSS-Oversight#12]
**Who is the primary user?**
State Officers

**What will this help them do?**
We have a preliminary health rubric that can be used to inform specific interactions between a state and SO.

**When is it needed?**
Relevant visibility are needed before the next round of testing with SOs

**What steps are needed to make it a reality?**

- [ ] Confirm which are needed before piloting. 

May include the following:
- [x] Funding Request
- [x] RFP/Contract reviews
- [ ] Roadmap/strategy updates
- [ ] Demos
- [ ] Regular checkins

**Comment by alexpandel** [comment]
closing this one in favor of #8, since we'll be using [the Rosetta Stone](https://app.mural.co/t/gsa6/m/gsa6/1555081183659/ea413b6e817842720ed83114f670c337215a78bc) as the basis for many of the DDI-related visibility points, and this issue is relatively nebulously scoped. For reference, other potential visibility points are captured [here.🔒](https://docs.google.com/document/d/1W0luHCE69XQwfuuIA4dueLBwZOkMP28LA4VxmvZ0vgM/edit#heading=h.uzpc6uksdltr)
